// Decompiled with JetBrains decompiler
// Type: Camstar.WCF.ObjectStack.ServiceDetails_Info
// Assembly: Camstar.WCFClient, Version=7.7.7004.31021, Culture=neutral, PublicKeyToken=null
// MVID: CA19AA1B-EA44-4AB0-A5CC-92D7FB49DA91
// Assembly location: E:\WCFServicesGenerator\Camstar.WCFClient.dll

using System;
using System.Runtime.Serialization;

namespace Camstar.WCF.ObjectStack
{
  [KnownType(typeof (AvailableLotDetail_Info))]
  [KnownType(typeof (EventFailureDetail_Info))]
  [KnownType(typeof (ChecklistEntryDetails_Info))]
  [KnownType(typeof (AttachDocumentDetails_Info))]
  [KnownType(typeof (EventFailureCauseDetail_Info))]
  [KnownType(typeof (DPCollectionSampleDetail_Info))]
  [KnownType(typeof (EventFailureActionDetail_Info))]
  [KnownType(typeof (MaintReqActivationDetails_Info))]
  [KnownType(typeof (TargetDeploymentDetail_Info))]
  [KnownType(typeof (NCRUpdateDetail_Info))]
  [KnownType(typeof (EventLogDetail_Info))]
  [KnownType(typeof (NCRCommentsDetails_Info))]
  [KnownType(typeof (ComputationDetail_Info))]
  [KnownType(typeof (QualityCrossRefDetail_Info))]
  [KnownType(typeof (EventCheckBoxField_Info))]
  [KnownType(typeof (CAPADetail_Info))]
  [KnownType(typeof (ContainerHistoryInquiryDetail_Info))]
  [KnownType(typeof (DispositionDetail_Info))]
  [KnownType(typeof (QualityCustomDetail_Info))]
  [KnownType(typeof (FailureDetails_Info))]
  [KnownType(typeof (ApprovalSheetDetails_Info))]
  [KnownType(typeof (FailureCauseDetails_Info))]
  [KnownType(typeof (SuspectDeviceDetail_Info))]
  [KnownType(typeof (FailurePlanDetails_Info))]
  [KnownType(typeof (ComputationParamDetail_Info))]
  [KnownType(typeof (ReorderProcessObjectDetail_Info))]
  [KnownType(typeof (CustomerDetail_Info))]
  [KnownType(typeof (DecisionTreeDetail_Info))]
  [KnownType(typeof (ApprovalEntryDetails_Info))]
  [KnownType(typeof (QualityCrossReferenceDetail_Info))]
  [KnownType(typeof (PrintLabelDetails_Info))]
  [KnownType(typeof (CPModelingInstanceDtl_Info))]
  [KnownType(typeof (CombineFromDetail_Info))]
  [KnownType(typeof (PermissionDetail_Info))]
  [KnownType(typeof (CompleteMaintDetails_Info))]
  [KnownType(typeof (ComponentDistributeDestination_Info))]
  [KnownType(typeof (RecordSPCViolationDetail_Info))]
  [KnownType(typeof (ChangePackageDetail_Info))]
  [KnownType(typeof (SPCViolationDetail_Info))]
  [KnownType(typeof (IssueActualDetail_Info))]
  [KnownType(typeof (ESigProcessTimerServiceDetail_Info))]
  [DataContract(Namespace = "Camstar.WCF.ObjectStack")]
  [KnownType(typeof (ThruputDetail_Info))]
  [KnownType(typeof (DictionaryServiceDetail_Info))]
  [KnownType(typeof (ChangeQtyDetails_Info))]
  [KnownType(typeof (IssueDetails_Info))]
  [KnownType(typeof (ESigServiceDetail_Info))]
  [KnownType(typeof (LabelCategoryDetails_Info))]
  [KnownType(typeof (ESigCaptureDetail_Info))]
  [KnownType(typeof (UserQueryParameterValues_Info))]
  [KnownType(typeof (CompletedTaskDetail_Info))]
  [KnownType(typeof (TargetSystemDetail_Info))]
  [KnownType(typeof (RemovalCandidate_Info))]
  [KnownType(typeof (ChgContainerAttrDetail_Info))]
  [KnownType(typeof (RemovalDetail_Info))]
  [KnownType(typeof (LabelSummary_Info))]
  [KnownType(typeof (ComponentReplaceDetail_Info))]
  [KnownType(typeof (CollectSamplingDataDetails_Info))]
  [KnownType(typeof (ContainerAttrDetail_Info))]
  [KnownType(typeof (CollaboratorDetails_Info))]
  [KnownType(typeof (DefectDetail_Info))]
  [KnownType(typeof (SamplingDataPointDetails_Info))]
  [KnownType(typeof (LabelDetails_Info))]
  [KnownType(typeof (QualityESigDetail_Info))]
  [KnownType(typeof (DispositionSummary_Info))]
  [KnownType(typeof (SerializeDetails_Info))]
  [KnownType(typeof (EventDetail_Info))]
  [KnownType(typeof (StartDetails_Info))]
  [KnownType(typeof (ParametricData_Info))]
  [KnownType(typeof (StartContainerAttributeDetail_Info))]
  [KnownType(typeof (RegulatoryReportDetail_Info))]
  [KnownType(typeof (SplitDetails_Info))]
  [KnownType(typeof (CollaboratorEntryDetails_Info))]
  [KnownType(typeof (AttachedDocDetail_Info))]
  [KnownType(typeof (ExecuteChecklistDetail_Info))]
  [KnownType(typeof (EventLotDetail_Info))]
  [KnownType(typeof (DPCollectionGroupDetail_Info))]
  [KnownType(typeof (NCRDefectDetails_Info))]
  [KnownType(typeof (ExecuteChklstResponseDtl_Info))]
  [KnownType(typeof (EventDataDetails_Info))]
  [KnownType(typeof (EventComponentDetail_Info))]
  [KnownType(typeof (IssueActuals_Info))]
  [KnownType(typeof (EventDispositionDetail_Info))]
  [KnownType(typeof (ChangeAttributeDetails_Info))]
  [KnownType(typeof (DPCollectionPointDetail_Info))]
  [Serializable]
  public class ServiceDetails_Info : ServiceData_Info
  {
  }
}
