// Decompiled with JetBrains decompiler
// Type: Camstar.WCF.ObjectStack.ServiceDetails_Environment
// Assembly: Camstar.WCFClient, Version=7.7.7004.31021, Culture=neutral, PublicKeyToken=null
// MVID: CA19AA1B-EA44-4AB0-A5CC-92D7FB49DA91
// Assembly location: E:\WCFServicesGenerator\Camstar.WCFClient.dll

using System;
using System.Runtime.Serialization;

namespace Camstar.WCF.ObjectStack
{
  [KnownType(typeof (AttachDocumentDetails_Environment))]
  [KnownType(typeof (ESigProcessTimerServiceDetail_Environment))]
  [KnownType(typeof (SPCViolationDetail_Environment))]
  [KnownType(typeof (DispositionDetail_Environment))]
  [KnownType(typeof (UserQueryParameterValues_Environment))]
  [KnownType(typeof (ChgContainerAttrDetail_Environment))]
  [KnownType(typeof (CollectSamplingDataDetails_Environment))]
  [KnownType(typeof (SamplingDataPointDetails_Environment))]
  [KnownType(typeof (QualityESigDetail_Environment))]
  [KnownType(typeof (EventDetail_Environment))]
  [KnownType(typeof (RegulatoryReportDetail_Environment))]
  [KnownType(typeof (EventDataDetails_Environment))]
  [KnownType(typeof (EventLotDetail_Environment))]
  [KnownType(typeof (NCRDefectDetails_Environment))]
  [KnownType(typeof (EventComponentDetail_Environment))]
  [KnownType(typeof (EventDispositionDetail_Environment))]
  [KnownType(typeof (EventFailureDetail_Environment))]
  [KnownType(typeof (EventFailureCauseDetail_Environment))]
  [KnownType(typeof (EventFailureActionDetail_Environment))]
  [KnownType(typeof (EventLogDetail_Environment))]
  [KnownType(typeof (EventCheckBoxField_Environment))]
  [KnownType(typeof (QualityCustomDetail_Environment))]
  [KnownType(typeof (SuspectDeviceDetail_Environment))]
  [KnownType(typeof (CustomerDetail_Environment))]
  [KnownType(typeof (PrintLabelDetails_Environment))]
  [KnownType(typeof (CombineFromDetail_Environment))]
  [KnownType(typeof (PermissionDetail_Environment))]
  [KnownType(typeof (IssueActualDetail_Environment))]
  [KnownType(typeof (CompletedTaskDetail_Environment))]
  [KnownType(typeof (RemovalCandidate_Environment))]
  [KnownType(typeof (RemovalDetail_Environment))]
  [KnownType(typeof (ComponentReplaceDetail_Environment))]
  [KnownType(typeof (ContainerAttrDetail_Environment))]
  [KnownType(typeof (DefectDetail_Environment))]
  [DataContract(Namespace = "Camstar.WCF.ObjectStack")]
  [KnownType(typeof (SerializeDetails_Environment))]
  [KnownType(typeof (StartDetails_Environment))]
  [KnownType(typeof (StartContainerAttributeDetail_Environment))]
  [KnownType(typeof (SplitDetails_Environment))]
  [KnownType(typeof (ChangeAttributeDetails_Environment))]
  [KnownType(typeof (AttachedDocDetail_Environment))]
  [KnownType(typeof (ChecklistEntryDetails_Environment))]
  [KnownType(typeof (MaintReqActivationDetails_Environment))]
  [KnownType(typeof (NCRUpdateDetail_Environment))]
  [KnownType(typeof (NCRCommentsDetails_Environment))]
  [KnownType(typeof (QualityCrossRefDetail_Environment))]
  [KnownType(typeof (CAPADetail_Environment))]
  [KnownType(typeof (FailureDetails_Environment))]
  [KnownType(typeof (FailureCauseDetails_Environment))]
  [KnownType(typeof (FailurePlanDetails_Environment))]
  [KnownType(typeof (ReorderProcessObjectDetail_Environment))]
  [KnownType(typeof (DecisionTreeDetail_Environment))]
  [KnownType(typeof (QualityCrossReferenceDetail_Environment))]
  [KnownType(typeof (CompleteMaintDetails_Environment))]
  [KnownType(typeof (RecordSPCViolationDetail_Environment))]
  [KnownType(typeof (ChangeQtyDetails_Environment))]
  [KnownType(typeof (TargetSystemDetail_Environment))]
  [KnownType(typeof (ThruputDetail_Environment))]
  [KnownType(typeof (ComponentDistributeDestination_Environment))]
  [KnownType(typeof (ContainerHistoryInquiryDetail_Environment))]
  [KnownType(typeof (CPModelingInstanceDtl_Environment))]
  [KnownType(typeof (TargetDeploymentDetail_Environment))]
  [KnownType(typeof (IssueDetails_Environment))]
  [KnownType(typeof (DictionaryServiceDetail_Environment))]
  [KnownType(typeof (IssueActuals_Environment))]
  [KnownType(typeof (LabelCategoryDetails_Environment))]
  [KnownType(typeof (DispositionSummary_Environment))]
  [KnownType(typeof (CollaboratorDetails_Environment))]
  [KnownType(typeof (CollaboratorEntryDetails_Environment))]
  [KnownType(typeof (ESigServiceDetail_Environment))]
  [KnownType(typeof (ESigCaptureDetail_Environment))]
  [KnownType(typeof (LabelSummary_Environment))]
  [KnownType(typeof (LabelDetails_Environment))]
  [KnownType(typeof (ParametricData_Environment))]
  [KnownType(typeof (DPCollectionGroupDetail_Environment))]
  [KnownType(typeof (DPCollectionPointDetail_Environment))]
  [KnownType(typeof (DPCollectionSampleDetail_Environment))]
  [KnownType(typeof (ComputationDetail_Environment))]
  [KnownType(typeof (ComputationParamDetail_Environment))]
  [KnownType(typeof (ChangePackageDetail_Environment))]
  [KnownType(typeof (AvailableLotDetail_Environment))]
  [KnownType(typeof (ExecuteChecklistDetail_Environment))]
  [KnownType(typeof (ExecuteChklstResponseDtl_Environment))]
  [KnownType(typeof (ApprovalSheetDetails_Environment))]
  [KnownType(typeof (ApprovalEntryDetails_Environment))]
  [Serializable]
  public class ServiceDetails_Environment : ServiceData_Environment
  {
  }
}
