// Decompiled with JetBrains decompiler
// Type: Camstar.WCF.Services.ShopFloorMethods
// Assembly: Camstar.WCFClient, Version=7.7.7004.31021, Culture=neutral, PublicKeyToken=null
// MVID: CA19AA1B-EA44-4AB0-A5CC-92D7FB49DA91
// Assembly location: E:\WCFServicesGenerator\Camstar.WCFClient.dll

using Camstar.WCF.ObjectStack;
using System;
using System.Runtime.Serialization;

namespace Camstar.WCF.Services
{
  [DataContract(Namespace = "Camstar.WCF.ObjectStack")]
  [Serializable]
  public enum ShopFloorMethods
  {
    [EnumMember, Enumeration(null)] AccumulateSummaryHistoryData,
    [EnumMember, Enumeration(null)] AddESigRequirement,
    [Enumeration(null), EnumMember] AddHistorySummary,
    [EnumMember, Enumeration(null)] AddMassUpdateStatement,
    [Enumeration(null), EnumMember] AddTrainingRequirmentsToESigRequirements,
    [EnumMember, Enumeration(null)] ApplyDetails,
    [Enumeration(null), EnumMember] ApplyParametricDetails,
    [EnumMember, Enumeration(null)] ApplyServiceDetail,
    [Enumeration(null), EnumMember] ApplyServiceDetails,
    [EnumMember, Enumeration(null)] AuthorizeSigner,
    [EnumMember, Enumeration(null)] CheckRolePermissions,
    [EnumMember, Enumeration(null)] CreateHistoryMainline,
    [Enumeration(null), EnumMember] CreateParametricData,
    [EnumMember, Enumeration(null)] DataPointConvertListToResultset,
    [EnumMember, Enumeration(null)] DownloadFile,
    [Enumeration(null), EnumMember] EnforceDispatchRule,
    [Enumeration(null), EnumMember] EvaluateLabelTags,
    [EnumMember, Enumeration(null)] Execute,
    [EnumMember, Enumeration(null)] Execute_User,
    [Enumeration(null), EnumMember] ExecuteTransactionTask,
    [Enumeration(null), EnumMember] FinishModifyingEntity,
    [EnumMember, Enumeration(null)] GetActions,
    [Enumeration(null), EnumMember] GetAttributeParent,
    [EnumMember, Enumeration(null)] GetComputation,
    [Enumeration(null), EnumMember] GetComputationParams,
    [EnumMember, Enumeration(null)] GetComputationParamsForDataPoints,
    [Enumeration(null), EnumMember] GetDataPointListSelectionValues,
    [Enumeration(null), EnumMember] GetDataPointObjectGroupSelectionValues,
    [EnumMember, Enumeration(null)] GetDataPointQuerySelectionValues,
    [EnumMember, Enumeration(null)] GetDataPoints,
    [EnumMember, Enumeration(null)] GetDataPointStaticSelectionValues,
    [EnumMember, Enumeration(null)] GetDefaultDispatchList,
    [EnumMember, Enumeration(null)] GetDispatchList,
    [Enumeration(null), EnumMember] GetDispatchObject,
    [Enumeration(null), EnumMember] GetESigRequirementFromSpec,
    [EnumMember, Enumeration(null)] GetESigRequirements,
    [EnumMember, Enumeration(null)] GetESigRequirementsFromTxnMap,
    [Enumeration(null), EnumMember] GetLabelInformation,
    [Enumeration(null), EnumMember] GetLabelInformationFromLabelMap,
    [Enumeration(null), EnumMember] GetLabelInformationFromPrinterLabel,
    [EnumMember, Enumeration(null)] GetTrainingRecord,
    [EnumMember, Enumeration(null)] GetTrainingRequirements,
    [Enumeration(null), EnumMember] GetWIPMsgs,
    [EnumMember, Enumeration(null)] InitDispatchQueryParams,
    [Enumeration(null), EnumMember] InitializeHistoryMainline,
    [EnumMember, Enumeration(null)] Load,
    [Enumeration(null), EnumMember] LoadESigDetails,
    [Enumeration(null), EnumMember] ModifyEntity,
    [Enumeration(null), EnumMember] OverrideDispatchEnforcement,
    [EnumMember, Enumeration(null)] PreExecute_User,
    [Enumeration(null), EnumMember] PreValidate,
    [EnumMember, Enumeration(null)] PreValidate_Generic,
    [EnumMember, Enumeration(null)] PreValidate_Specific,
    [Enumeration(null), EnumMember] PreValidate_User,
    [EnumMember, Enumeration(null)] PrintLabel,
    [Enumeration(null), EnumMember] ProcessAfterCommit,
    [EnumMember, Enumeration(null)] ProcessAfterCommit_User,
    [Enumeration(null), EnumMember] ProcessApplicationExtensions,
    [Enumeration(null), EnumMember] ProcessComputation,
    [Enumeration(null), EnumMember] ProcessComputationParams,
    [EnumMember, Enumeration(null)] ProcessElectronicProcedures,
    [EnumMember, Enumeration(null)] ProcessElectronicSignatures,
    [Enumeration(null), EnumMember] ProcessLabelInformation,
    [EnumMember, Enumeration(null)] ProcessMaintenanceMgmt,
    [Enumeration(null), EnumMember] ProcessMasterRecipe,
    [Enumeration(null), EnumMember] ProcessNonConformances,
    [EnumMember, Enumeration(null)] RecordMainlinePostHistory,
    [Enumeration(null), EnumMember] RecordMainlinePreHistory,
    [EnumMember, Enumeration(null)] RecordPostHistory,
    [EnumMember, Enumeration(null)] RecordPreHistory,
    [EnumMember, Enumeration(null)] RecordSummaryPostHistory,
    [EnumMember, Enumeration(null)] RecordSummaryPreHistory,
    [Enumeration(null), EnumMember] ReplaceHistoryMainline,
    [Enumeration(null), EnumMember] ReplaceOldHistoryMainline,
    [Enumeration(null), EnumMember] ResolveParametricData,
    [EnumMember, Enumeration(null)] RetrieveCalendarShift,
    [Enumeration(null), EnumMember] Sampling_ContainerSampleData,
    [Enumeration(null), EnumMember] Sampling_EvaluateSwitchingRule,
    [Enumeration(null), EnumMember] Sampling_GetDistributionListRecipients,
    [EnumMember, Enumeration(null)] Sampling_LotSampleData,
    [Enumeration(null), EnumMember] Sampling_SendSwitchingRuleNotification,
    [EnumMember, Enumeration(null)] Sampling_SetupSampling,
    [EnumMember, Enumeration(null)] Sampling_SetupSamplingRequirement,
    [EnumMember, Enumeration(null)] SetHistoryMainlineTxnDates,
    [Enumeration(null), EnumMember] StartModifyingEntity,
    [EnumMember, Enumeration(null)] UpdateCompletionMsg_PrintLabelFailure,
    [EnumMember, Enumeration(null)] UpdateCompletionMsg_PrintLabelSuccess,
    [Enumeration(null), EnumMember] Validate,
    [EnumMember, Enumeration(null)] Validate_Generic,
    [Enumeration(null), EnumMember] Validate_Specific,
    [EnumMember, Enumeration(null)] Validate_User,
    [Enumeration(null), EnumMember] ValidateApplicationExtensions,
    [EnumMember, Enumeration(null)] ValidateElectronicProcedures,
    [Enumeration(null), EnumMember] ValidateElectronicSignatures,
    [Enumeration(null), EnumMember] ValidateESigRequirement,
    [Enumeration(null), EnumMember] ValidateMaintenanceMgmt,
    [EnumMember, Enumeration(null)] ValidateMaintenanceUOM,
    [EnumMember, Enumeration(null)] ValidateMasterRecipe,
    [EnumMember, Enumeration(null)] ValidateNonConformances,
    [Enumeration(null), EnumMember] ValidateResourceMaintenance,
    [EnumMember, Enumeration(null)] ValidateTrainingRequirement,
    [EnumMember, Enumeration(null)] ValidateTrainingRequirements,
    [Enumeration(null), EnumMember] VerifyPasswordSignature,
    [EnumMember, Enumeration(null)] ExecuteTransaction,
    [Enumeration(null), EnumMember] AddDataTransaction,
  }
}
